### ISSUE TITLE
CSV file is not getting uploaded

### ISSUE THREAD

**Issue by sapnadudhat03** [wpeventmanager/wp-event-manager-migration#1]
![migration](https://user-images.githubusercontent.com/49863477/82809151-bacf1e00-9e8b-11ea-9394-8fd4f488c54b.png)

**Comment by ritakikani** [comment]
This issue resolve in current version.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed & working fine.

CSV file is uploaded without issue.

So I closed the issue.
