### ISSUE TITLE
Venue and organizer is not linking. 

### ISSUE THREAD

**Issue by Priya-Goenka** [wpeventmanager/wp-event-manager-migration#10]
Venue and organizer is not being added to the events, when imported.

**Comment by mistry-jignesh** [comment]
Verified this issue. Now When import event , here added  Venue & organizer details.

![image](https://user-images.githubusercontent.com/75515088/190377594-bff22ad3-9b5e-433f-a5a0-804c084c00f1.png)

Then after details are missing.

![image](https://user-images.githubusercontent.com/75515088/190377692-a985d246-ac69-4daf-968a-d1bf2531a70e.png)

**Comment by mistry-jignesh** [comment]
Verified this issue. This issue is working.
Venue and organizer is linking to the events, when imported.

Organizer & venue is added with event .So I closed the issue
