### ISSUE TITLE
Expired event is not import

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#12]
Expired event is not import.

Before import event list.

![image](https://user-images.githubusercontent.com/75515088/193739285-2bfa78b7-d214-4a5c-884d-e2d1e7ea9130.png)

**After import event list.**

![image](https://user-images.githubusercontent.com/75515088/193739367-c2af2822-b284-403c-8970-8dce0a41270e.png)

**Comment by ritakikani** [comment]
Here, all events are properly import which is listed in .csv file.
It don't check that event is expired or active.so please check in the .csv file which you trying to import that the event which is expired is really inside the file or not.

**Comment by mistry-jignesh** [comment]
Verified this issue . Expired event is not export.

WP all export plugin try to export expired event but it is display below messsage.

![image](https://user-images.githubusercontent.com/75515088/202694502-b80e1946-0abe-4e53-b580-7490b03f3d9f.png)

So Expired events is not import here.
