### ISSUE TITLE
Import organizer- Warning message is display 

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#13]
Import organizer- Warning message is display .
![image](https://user-images.githubusercontent.com/75515088/193741192-5af44624-0284-4b38-81f5-97716d2a6603.png)

**Comment by mistry-jignesh** [comment]
Facing same issue . Warning message is display .

![image](https://user-images.githubusercontent.com/75515088/202696480-493101b8-8b88-4020-a446-3ca7c05cf5eb.png)

**Comment by ritakikani** [comment]
This issue already resolve so please take latest and test again.

**Comment by mistry-jignesh** [comment]
I have verified this issue using updated plugin. Now this error message is not facing in the updated version.

This issue is fixed & working fine . So I closed the issue.
