### ISSUE TITLE
Venue logo image & Event location Map is not display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#14]
Export below Field.

Here organizer logo is set properly.

![image](https://user-images.githubusercontent.com/75515088/193745381-5a6b0033-2427-431f-b926-ed97e0d91868.png)

Venue logo image & Event location Map is not display.

![image](https://user-images.githubusercontent.com/75515088/193745065-51e9583e-19cc-44c6-87d0-4ac5850a97ee.png)

**Comment by ritakikani** [comment]
event location is working fine, please check again.

![image](https://user-images.githubusercontent.com/25837982/202151293-1346d60b-ed51-476c-8065-c85903bf436f.png)

**Comment by mistry-jignesh** [comment]
Verified this location is display properly on the details page.

Facing issue in the venue logo. This issue may be face because of issue #15 .

After that may be issue will fixed. This issue will closed after issue #15 is fixed.

**Comment by mistry-jignesh** [comment]
Verified this issue. Location and Venue logo issue is working properly.

I have veriifed this issue  https://github.com/wpeventmanager/wp-event-manager/issues/1279 .

This issue is resloved . So I closed it.
