### ISSUE TITLE
Select field not display on the event details page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#16]
Select field not display on the event details page.

I have select Start date ,End date,Start time, End time, Event Description ,Organizer, Event type and Category.

Please check other field for events.

![image](https://user-images.githubusercontent.com/75515088/193795738-ebf571b5-06be-49c8-a855-df501a3bdadc.png)

**Comment by ritakikani** [comment]
Here, all fields are display properly which is inside inport .csv file and set at inport event time.

![image](https://user-images.githubusercontent.com/25837982/202158397-480f0422-3eda-466d-a886-30b6abe4c92c.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is working fine.

Select field are display on the event details page.

So I closed the issue.
