### ISSUE TITLE
Event thumbnail is missing at event listing page after inport event for imported events only

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#18]
![image](https://user-images.githubusercontent.com/25837982/202163242-ac8b0b15-c1c6-4a27-9595-3fb983204948.png)

**Comment by ritakikani** [comment]
This issue is related to core plugin.so, please check this https://github.com/wpeventmanager/wp-event-manager/issues/1277

**Comment by mistry-jignesh** [comment]
Verified this issue using updated core plugin.Now this issue is fixed and working fine.

Event thumnnail is working fine at listing page after import event.

So I closed the issue.
