### ISSUE TITLE
Upload xls file.

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#19]
Upload xls file.

**Comment by mistry-jignesh** [comment]
Verified this issue. Need to check  I have downloaded Organizer and Venue XLS file from the staging server.

Try to uploaded on the local server but error message is display.

![image](https://user-images.githubusercontent.com/75515088/205050638-32b54e39-f9b7-4a28-85f2-73d64d75a8dc.png)

**Also same file save as but file is uploaded and in the mapping field are display special symbol.**

**Comment by mistry-jignesh** [comment]
This issue is alreday open in the export addon. 

Issue id issue.

https://github.com/wpeventmanager/wp-event-manager-export/issues/64

**Comment by ritakikani** [comment]
This is not issue of plugin but it is from wordpress setup.Is is not allowing to upload .xls file in your setup so you need to first change the settings.

For that you can write the below code in your theme functions.php file.
`function my_custom_mime_types( $mimes ) {
$mimes['csv'] = 'text/csv';
unset( $mimes['exe'] );
 return $mimes;
}
add_filter( 'upload_mimes', 'my_custom_mime_types' );`

or write below code in wp-config.php file.
`define('ALLOW_UNFILTERED_UPLOADS', true);`
