### ISSUE TITLE
Venue/organizer logo not upload during import

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#21]
Venue/organizer logo not upload during import

**Comment by mistry-jignesh** [comment]
Verified this issue . After import file Venue/organizer logo not upload .

Please check it .

**Comment by ritakikani** [comment]
This is not issue from migration but it is from export addon.

**Comment by mistry-jignesh** [comment]
This issue is from export addon. I have created issue in the export adddon.
Issue number as below.
https://github.com/wpeventmanager/wp-event-manager-export/issues/65
