### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#23]
Please check the doc for code cleanup info.

[migration.docx](https://github.com/wpeventmanager/wp-event-manager-migration/files/10140496/migration.docx)

**Comment by mistry-jignesh** [comment]
Need to verify below issue. #25,#26.

**Comment by ritakikani** [comment]
the above mention both issues are resolve now.

**Comment by mistry-jignesh** [comment]
Currently issue #26  is fixed and working fine.

#25 issue is depend on the issue #30. After that I will closed the this issue.

**Comment by mistry-jignesh** [comment]
Issue #25 and #30 both issues are working fine. 
Once finishe all steps for testing for migration then I will closed the issue.

**Comment by mistry-jignesh** [comment]
Verified all fixed issues are working fine. So Closed the issue.
