### ISSUE TITLE
Edit event - Venue section -Warning message is display

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#24]
Events are imported sucessfully.

After import events file .

Edit event - Venue section -Warning message is display.

![image](https://user-images.githubusercontent.com/75515088/205839272-1681014a-dd4f-495f-8b0b-b05ffd8bdc67.png)

**Comment by ritakikani** [comment]
this issue is resolve in https://github.com/wpeventmanager/wp-event-manager-migration/issues/25

**Comment by mistry-jignesh** [comment]
Verified this issue . Now warning error message issue is fixed & working properly.

So I closed the issue.
