### ISSUE TITLE
Venue and organizer not selected

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#25]
After import events .

Here related events venue & organizer are selected.

![image](https://user-images.githubusercontent.com/75515088/205847458-e14c441f-20f2-4b28-a39d-b145c8b72a24.png)

**Comment by mistry-jignesh** [comment]
Verified  this issue. Issue are fixed and facing issue in the venue.

![image](https://user-images.githubusercontent.com/75515088/208068490-75764c01-4390-4d31-9899-e8b085d72ee6.png)

After import events . Here related events venue not selected.

**Comment by ritakikani** [comment]
After resolve https://github.com/wpeventmanager/wp-event-manager-export/issues/68 and https://github.com/wpeventmanager/wp-event-manager-export/issues/65, the above issue is resolve so please take latest code of export and migration plugin and verify again.

**Comment by mistry-jignesh** [comment]
This issue is verify after issue #30 fixed. Now I am not closed the issue.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.
While import XML file then venue & organizer are display selected.

![image](https://user-images.githubusercontent.com/75515088/210308268-c2f332b9-ae06-4270-a665-5cd9b6e0c52c.png)
