### ISSUE TITLE
Default mapping of post id with ID field

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#26]
Default mapping of post id with ID field

![image](https://user-images.githubusercontent.com/25837982/207021762-7133911b-c104-4a7d-a2c0-2f1b7a323271.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . When import venue then post id field is missing.

Need to check it.

**Comment by ritakikani** [comment]
this issue is resolve in https://github.com/wpeventmanager/wp-event-manager-export/issues/68.
please take latest of export and migration plugin code and verify it.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.
Post id is availabel while import venue.
This issue is working fine.

![image](https://user-images.githubusercontent.com/75515088/210060420-bd46b084-2279-402b-8146-2f4c26b04e93.png)

So I closed the issue.
