### ISSUE TITLE
Need to read tags for organizer and venue from xml import file

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#29]
Need to read tags for organizer and venue from xml import file

**Comment by mistry-jignesh** [comment]
Verified this issue . While import event file , In the select field tag option is missing .

Here I am not able to select tag option .

![image](https://user-images.githubusercontent.com/75515088/210062203-7b989155-1a9f-40c7-8424-f11d2abfb2be.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . While import event file , In the select field tag option is availabel.

This issue is fixed. So I closed the issue.
