### ISSUE TITLE
Deafault Event CSV/xml - Events are not imported

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#30]
Try to import  Default event CSV/xml but events are not imported .

On the screen is display the messgae Events Successfully Import .

![image](https://user-images.githubusercontent.com/75515088/210052845-a71e4e52-c246-4130-a9db-eb21daca175a.png)

But in the all events option display the mesage "**_No Events found_**"

![image](https://user-images.githubusercontent.com/75515088/210053117-c2236b9c-9c00-4586-b4d7-4bcc95229732.png)

**Comment by ritakikani** [comment]
this is working fine so please take latest code from the git and test again with refresh csv/xml file which you never import in your setup. The issue may be their if you already import the events previous from the same csv/xml file then again the same events will not be imported.For that you must need to permanently delete the older events.

**Comment by mistry-jignesh** [comment]
Verified this issue. Try to import Default event CSV/xml file then events are imported .
This issue is working fine. So I closed the issue.
