### ISSUE TITLE
Registration option is not working

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#34]
Registration option is not working.

![image](https://user-images.githubusercontent.com/121149500/218077445-b112fa0e-93f8-48af-9767-a116ba211e5c.png)

**Comment by ritakikani** [comment]
Need to discuss with @krinaydhanani

**Comment by mistry-jignesh** [comment]
I verified this issue. Data are imported successfully.

![Registration1](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/ef3e65bc-5b44-438b-842e-fee0ea28ee09)

But go to the registration section at backend then the attended data does not Sync.
Need to check this issue.

![Registration1](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/f0c58bc3-f237-40d5-aac5-282d7bd405e7)

-----------------------------------------------------------------------------------------------------------------------------------

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/3b2a02f1-7e2f-4c72-ad73-1e2cc3d3c5e6)

**Comment by mistry-jignesh** [comment]
I verified this issue. Data are imported successfully.  

Here display the numeric values.

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/c5887635-ab84-42b6-a35b-66e3424e0aa8)


Now at the backend go to the registration section event name is missing,


![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/eea40447-f9aa-466d-9a37-c31398830bc5)

Frontend section Attendee data are missing.

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/de02510f-25b2-4245-9068-9fbda7d84188)

**Comment by mistry-jignesh** [comment]
I verified this issue .Now  above issues are fixed.
It is working fine . So I closed the issue.
