### ISSUE TITLE
Migration box line should be proper

### ISSUE THREAD

**Issue by patel-nimesh** [wpeventmanager/wp-event-manager-migration#35]
![image](https://user-images.githubusercontent.com/121149500/218084348-93fef369-ebe1-43a8-ab83-3f83e00b4c79.png)

**Comment by mistry-jignesh** [comment]
I verified this issue. Now this issue is fixed.
Box line is displayed properly.

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/cbd3f889-41be-4048-9a11-b156da125dd5)

So I closed the issue.
