### ISSUE TITLE
Langauge translation issue

### ISSUE THREAD

**Issue by ritakikani** [wpeventmanager/wp-event-manager-migration#39]
Langauge translation issue

**Comment by mistry-jignesh** [comment]
**Venues :** 
![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/40615979-cd23-4789-b39d-a6c1600a5fbb)

**Organizer** 

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/2a872ede-c0ec-4227-9a04-668c9036fcca)

**Registration** 

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/a4682044-d8a4-4564-9357-e103a5dab6ee)

**Comment by ritakikani** [comment]
This is from core plugin, not an export plugin issue.

**Comment by mistry-jignesh** [comment]
As per @ritakikani  : This is from core plugin, not an migration plugin issue.
So I closed the issue.
