### ISSUE TITLE
After delete migration plugin. Data are available in DB

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#41]
After delete migration plugin. Data are available in DB.

https://prnt.sc/lf1hXVF0ffmz

**Comment by ritakikani** [comment]
We stored files in wordpress media library as attachment only without any post type, so we cannot delete any post attachement.

**Comment by mistry-jignesh** [comment]
I verified this issue.  As per @ritakikani :  We stored files in WordPress media library as attachments only without any post type, so we cannot delete any post attachments.

So I closed the issue.
