### ISSUE TITLE
Import XML  file then dispaly the error message

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#42]
Import XML file : Organizer, Venues and Events file then error message.

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/48240f49-dbf9-4e27-907d-2c8ef91b61ef)

**Comment by ritakikani** [comment]
This is not error from plugin.This error is from wordpress, that this type of file is not allowed to upload. so, you have to write script to allow this mime-type to upload in your site.

**Comment by mistry-jignesh** [comment]
I have verified this issue. This issue is working fine with adding the above in the theme functions.php file.

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/38c9caf9-fa25-4deb-a9cb-186bb40ef8af)

So I closed the issue.

**Comment by ritakikani** [comment]
Also you can write below code in wp-config.php file instead of above function.This will allow all types of files to upload.

`define('ALLOW_UNFILTERED_UPLOADS', true);`
