### ISSUE TITLE
PHP 8.2 Deprecated code error

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#48]
Deprecated: Creation of dynamic property WP_Event_Manager_Alerts::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-alerts/wp-event-manager-alerts.php on line 88

Deprecated: Creation of dynamic property WPEM_Registrations::$post_types is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager-registrations/wp-event-manager-registrations.php on line 96

Deprecated: Creation of dynamic property WP_Event_Manager_Settings::$settings_group is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-settings.php on line 21

Deprecated: Creation of dynamic property WP_Event_Manager_Admin::$settings_page is deprecated in /home/wazzonau/public_html/wp-content/plugins/wp-event-manager/admin/wp-event-manager-admin.php on line 29

**Comment by ritakikani** [comment]
@mistry-jignesh Code review done from my side.

**Comment by mistry-jignesh** [comment]
I have verified issue. Now Deprecated code error is fixed.
So I closed the issue.
