### ISSUE TITLE
Export with migration is really important for easier for users

### ISSUE THREAD

**Issue by hiteshmakvana** [wpeventmanager/wp-event-manager-migration#6]
Currently user need to find export plugin to export the existing data in case if they want to import it using our plugin data.

WP Event Manager data and settings can be cloned using this process.

This is like cloning one site data to another site.

**Comment by krinaydhanani** [comment]
I need to understand this issue first and what is the requirement.

**Comment by ritakikani** [comment]
I think our Export plugin fill this requirement.
