### ISSUE TITLE
[ Bulk Import ] Registration with CSV

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager-migration#7]
Several other plugins and user are asking for bulk import where user can easily add the attendees from his end with CSV or in bulk.

To simplify this Make the registration import feature which event selection and upload registrations csv in it.

**Comment by mistry-jignesh** [comment]
Now registration data is imported using Registration option.

![image](https://github.com/wpeventmanager/wp-event-manager-migration/assets/75515088/c2cbf2fa-2bba-410f-b530-66079d0d9e6b)

So I closed the issue.
