### ISSUE TITLE
Data in not available 

### ISSUE THREAD

**Issue by yukta05** [wpeventmanager/wp-event-manager-migration#8]
![Screenshot_33](https://user-images.githubusercontent.com/86232676/138640151-1e9ac242-da23-4e07-ab15-a24d091d7b19.jpg)
![Screenshot_34](https://user-images.githubusercontent.com/86232676/138640158-8507af2b-9307-4503-837e-0f1c22b631af.jpg)

in step 2 and import page  data is not available for it.

**Comment by vijayrathod245** [comment]
It's working fine from my side.

**Comment by mistry-jignesh** [comment]
Verified this issue .Now this issue is fixed .

In the step 2 -Import page data is available .

![image](https://user-images.githubusercontent.com/75515088/190376466-3da6b257-5352-4ec2-9a81-fff9c3835f32.png)


So I closed the issue.

**Comment by mistry-jignesh** [comment]
Verified this issue. 

In the PHP Version 8 or updated version - It is not working

In the steps 2 :  Import page data is not available for it.

![image](https://user-images.githubusercontent.com/75515088/190380358-9a2be7ef-cc69-4b83-8879-7f67bb023b64.png)

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this issue is fixed.

Now It's working fine . In the steps 2 - Import page data is available.

So I closed the issue.
