### ISSUE TITLE
Fatal error: Uncaught Error in dispaly on the page

### ISSUE THREAD

**Issue by mistry-jignesh** [wpeventmanager/wp-event-manager-migration#9]
Issue with the Migration tool and now cannot access it. It says there has been a critical error on the website for that plugin page, but the error only shows for that plugin. There has been a critical error on this website.

Fatal error: Uncaught Error: Call to undefined function get_event_manager_template() in /var/www/vhosts/missionrodandgun.com/httpdocs/wp-content/plugins/wp-event-manager-migration/admin/wpem-migration-admin.php:223 Stack trace: #0 /var/www/vhosts/missionrodandgun.com/httpdocs/wp-includes/class-wp-hook.php(307): WPEM_Migration_Admin->event_migration('') #1 /var/www/vhosts/missionrodandgun.com/httpdocs/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #2 /var/www/vhosts/missionrodandgun.com/httpdocs/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #3 /var/www/vhosts/missionrodandgun.com/httpdocs/wp-admin/admin.php(259): do_action('toplevel_page_e...') #4 {main} thrown in /var/www/vhosts/missionrodandgun.com/httpdocs/wp-content/plugins/wp-event-manager-migration/admin/wpem-migration-admin.php on line 223

**Comment by kinjal6810** [comment]
![image](https://user-images.githubusercontent.com/104058202/180425437-90de33b3-b538-4850-b8cb-8b1142042bbe.png)
working properly from my side.

**Comment by mistry-jignesh** [comment]
Verified this issue . Now this error message is not display event migration page.

So I closed the issue.
